baseURL = "https://shiratatsu.com"
title = "Good Luck My Way!"
author = "Author"
theme = "inkblotty"
paginate = 10

languageCode = "en-us"
DefaultContentLanguage = "en-us"
hasCJKLanguage = "true"

enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

disqusShortname = ""
googleAnalytics = "UA-149283372-3"

summaryLength=150

[permalinks]
  post = "/:slug/"
  page = "/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "result"
  name = "Result"
  url = "/result/"
  weight = 20

[Params]
  readmore = true

[outputs]                          # c.f. https://gohugo.io/templates/output-formats/
  home = ["HTML", "RSS"]
  page =  ["HTML"]
  section =  ["HTML", "RSS"]
  taxonomyTerm =  ["HTML", "RSS"]
  taxonomy =  ["HTML", "RSS"]

[sitemap]
  filename = "sitemap.xml"  # c.f. https://gohugo.io/templates/sitemap-template/#configure-sitemap-xml

[params.sns]
  github = "shiratatsu44"
  twitter = "jxUQEj9XPCmPJ74"

pygmentsCodefences = true
pygmentsUseClasses = true
